version: '3'

services:
  multiplexer:
    build: .
    networks:
      - ns-stream
    ports:
      - '3000:${APP_PORT:-3000}'
    env_file: .env
    environment:
      - APP_PORT=3000

networks:
  ns-stream:
    external: true
